# Copyright (c) 2023 XiNGRZ
# SPDX-License-Identifier: MIT

description: Knob switch profile

compatible: "zmk,knob-profile-switch"

include: knob-profile.yaml

properties:
  on-off-distance-deg:
    type: int
    required: false
    default: 80
